<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Kraken</title>
</head>
<body>
    <div style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px;min-width:100%;padding:0px;text-align:left;width:100%!important;color:rgb(36,36,36)">
        <span style="box-sizing:border-box;font-size:1px;line-height:1px;max-height:0px;max-width:0px;opacity:0;overflow:hidden;font-family:Celias,Roboto,Arial,Verdana,sans-serif;display:none!important;color:rgb(238,238,238)">Somebody just tried to create another account with this email.</span>
        <table style="background-image:linear-gradient(rgb(238,238,238),rgb(238,238,238));border-collapse:collapse;border-spacing:0px;box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;height:100%;line-height:1.5em;margin:0px;padding:0px;text-align:left;vertical-align:top;width:100%;background-color:rgb(238,238,238);color:rgb(36,36,36)">
          <tbody style="font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif">
            <td align="center" valign="top" style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:auto;padding:0px;text-align:left;vertical-align:top;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)">
              <center style="box-sizing:border-box;min-width:600px;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif">
                <table align="center" style="background-image:linear-gradient(rgb(238,238,238),rgb(238,238,238));border-collapse:collapse;border-spacing:0px;box-sizing:border-box;float:none;margin:0px auto;max-width:1200px;padding:0px 2rem;text-align:center;vertical-align:top;width:600px;font-family:Celias,Roboto,Arial,Verdana,sans-serif;background-color:rgb(238,238,238)"><tbody style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><td style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px;padding:0px;text-align:left;vertical-align:top;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)">
                  <center style="box-sizing:border-box;min-width:600px;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif">
                    <span align="center" style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;color:rgb(137,137,137)">

                    </span>
                  </center>
                </td></tr></tbody></table>
              </center>
              <center style="box-sizing:border-box;min-width:600px;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif">

                <table align="center" style="border-collapse:collapse;border-spacing:0px;box-sizing:border-box;float:none;margin:0px auto;padding:0px;text-align:center;vertical-align:top;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tbody style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><td height="20" style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:20px;font-weight:normal;line-height:20px;margin:0px;padding:0px;text-align:left;vertical-align:top;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)">&nbsp;</td></tr></tbody></table>

                <table align="center" style="background-image:linear-gradient(rgb(238,238,238),rgb(238,238,238));border-collapse:collapse;border-spacing:0px;box-sizing:border-box;float:none;margin:0px auto;max-width:1200px;padding:0px 2rem;text-align:center;vertical-align:top;width:600px;font-family:Celias,Roboto,Arial,Verdana,sans-serif;background-color:rgb(238,238,238)"><tbody style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><td style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px;padding:0px;text-align:left;vertical-align:top;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)">

                <table style="border-collapse:collapse;border-spacing:0px;box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tbody style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><td height="20" style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:20px;font-weight:normal;line-height:20px;margin:0px;padding:0px;text-align:left;vertical-align:top;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)">&nbsp;</td></tr></tbody></table>

                <table style="border-collapse:collapse;border-spacing:0px;border-top-left-radius:15px;border-top-right-radius:15px;box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif;background-color:rgb(255,255,255)"><tbody style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><td height="30" style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:30px;font-weight:normal;line-height:30px;margin:0px;padding:0px;text-align:left;vertical-align:top;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)">&nbsp;</td></tr></tbody></table>

                <table style="border-collapse:collapse;border-spacing:0px;box-sizing:border-box;display:table;padding:0px;text-align:left;vertical-align:top;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif;background-color:rgb(255,255,255)"><tbody style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif">
                  <th style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px auto;padding:0px;text-align:left;vertical-align:top;width:50px;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)"><table style="border-collapse:collapse;border-spacing:0px;box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tbody style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><th style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px;padding:0px;text-align:left;vertical-align:top;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)"></th></tr></tbody></table></th>
                  <th style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px auto;padding:0px;text-align:left;vertical-align:top;width:200px;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)"><table style="border-collapse:collapse;border-spacing:0px;box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tbody style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><th style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px;padding:0px;text-align:left;vertical-align:top;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)">
                     <img src="https://ci4.googleusercontent.com/proxy/SbeF0VWMneCw9hj4jwcspfS0_uJuVC48eYyjgVc3kzIACv7BFAvebnqbfQzw8VaU1lXd5EgoodAfZD3yQmcffe3FEP3qsAvZSRhoNFAqcRgBZdqJ=s0-d-e1-ft#https://assets.kraken.com/marketing/emails/headers/Light-Logo.png" width="113" height="18" style="box-sizing:border-box;clear:both;display:block;max-width:100%;outline:none;text-decoration:none;width:auto;font-family:Celias,Roboto,Arial,Verdana,sans-serif" class="CToWUd" data-bit="iit">
                  </th></tr></tbody></table></th>
                  <th style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px auto;padding:0px;text-align:left;vertical-align:top;width:350px;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)"><table style="border-collapse:collapse;border-spacing:0px;box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tbody style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><th style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px;padding:0px;text-align:left;vertical-align:top;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)"></th></tr></tbody></table></th>
                </tr></tbody></table>

                <table style="border-collapse:collapse;border-spacing:0px;box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif;background-color:rgb(255,255,255)"><tbody style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><td height="30" style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:30px;font-weight:normal;line-height:30px;margin:0px;padding:0px;text-align:left;vertical-align:top;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)">&nbsp;</td></tr></tbody></table>


                <table style="border-collapse:collapse;border-spacing:0px;box-sizing:border-box;display:table;padding:0px;text-align:left;vertical-align:top;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif;background-color:rgb(255,255,255)"><tbody style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif">
                  <th style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px auto;padding:0px;text-align:left;vertical-align:top;width:50px;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)"><table style="border-collapse:collapse;border-spacing:0px;box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tbody style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><th style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px;padding:0px;text-align:left;vertical-align:top;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)"></th></tr></tbody></table></th>
                  <th style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px auto;padding:0px;text-align:left;vertical-align:top;width:500px;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)"><table style="border-collapse:collapse;border-spacing:0px;box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tbody style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><th style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px;padding:0px;text-align:left;vertical-align:top;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)">
                    <h1 style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Tahoma,sans-serif;font-size:30px;font-weight:700;line-height:1.5em;margin:0px;padding:0px;text-align:left;color:rgb(0,0,0)">  {!!  html_entity_decode($getMail->name) !!}
                </h1>
                  </th></tr></tbody></table></th>
                  <th style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px auto;padding:0px;text-align:left;vertical-align:top;width:50px;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)"><table style="border-collapse:collapse;border-spacing:0px;box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tbody style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><th style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px;padding:0px;text-align:left;vertical-align:top;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)"></th></tr></tbody></table></th>
                </tr></tbody></table>

                <table style="border-collapse:collapse;border-spacing:0px;box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif;background-color:rgb(255,255,255)"><tbody style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><td height="25" style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:25px;font-weight:normal;line-height:25px;margin:0px;padding:0px;text-align:left;vertical-align:top;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)">&nbsp;</td></tr></tbody></table>

                <table style="border-collapse:collapse;border-spacing:0px;box-sizing:border-box;display:table;padding:0px;text-align:left;vertical-align:top;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif;background-color:rgb(255,255,255)"><tbody style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif">
                    <th style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px auto;padding:0px;text-align:left;vertical-align:top;width:150px;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)"><table style="border-collapse:collapse;border-spacing:0px;box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tbody style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><th style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px;padding:0px;text-align:left;vertical-align:top;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)"></th></tr></tbody></table></th>
                    <th style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px auto;padding:0px;text-align:left;vertical-align:top;width:300px;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)"><table style="border-collapse:collapse;border-spacing:0px;box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tbody style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><th style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px;padding:0px;text-align:left;vertical-align:top;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)">
                        <center style="box-sizing:border-box;min-width:300px;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif">
                            <img src="https://ci3.googleusercontent.com/proxy/61iFDWmf7zfuDN0VewRZx_2-DOrqA65jrLPvwGA-ouAiUMV6Qaz7JQ4I7do-7UioBieOl-Qoo4oZcIqD1WnZlqwBn3eavtz8Tx2bt0i1xaEq6tZw9Hij0IbF5HkSIM6nDCPebw=s0-d-e1-ft#https://assets.kraken.com/marketing/emails/header-illustrations/Light-Caution.png" align="center" style="box-sizing:border-box;clear:both;display:block;float:none;margin:0px auto;max-width:100%;outline:none;text-align:center;text-decoration:none;width:auto;font-family:Celias,Roboto,Arial,Verdana,sans-serif" class="CToWUd a6T" data-bit="iit" tabindex="0"><div class="a6S" dir="ltr" style="opacity: 0.01; left: 576.5px; top: 675px;"><div id=":fk" class="T-I J-J5-Ji aQv T-I-ax7 L3 a5q" title="Download" role="button" tabindex="0" aria-label="Download attachment " jslog="91252; u014N:cOuCgd,Kr2w4b,xr6bB; 4:WyIjbXNnLWY6MTc3NDI0MTQwNTEyOTk3NzQ1MyIsbnVsbCxbXV0." data-tooltip-class="a1V" jsaction="JIbuQc:.CLIENT"><div class="akn"><div class="aSK J-J5-Ji aYr"></div></div></div></div>
                        </center>
                    </th></tr></tbody></table></th>
                    <th style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px auto;padding:0px;text-align:left;vertical-align:top;width:150px;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)"><table style="border-collapse:collapse;border-spacing:0px;box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tbody style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><th style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px;padding:0px;text-align:left;vertical-align:top;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)"></th></tr></tbody></table></th>
                </tr></tbody></table>

                <table style="border-collapse:collapse;border-spacing:0px;box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif;background-color:rgb(255,255,255)"><tbody style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><td height="25" style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:25px;font-weight:normal;line-height:25px;margin:0px;padding:0px;text-align:left;vertical-align:top;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)">&nbsp;</td></tr></tbody></table>

                <table style="border-collapse:collapse;border-spacing:0px;box-sizing:border-box;display:table;padding:0px;text-align:left;vertical-align:top;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif;background-color:rgb(255,255,255)"><tbody style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif">
                  <th style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px auto;padding:0px;text-align:left;vertical-align:top;width:50px;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)"><table style="border-collapse:collapse;border-spacing:0px;box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tbody style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><th style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px;padding:0px;text-align:left;vertical-align:top;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)"></th></tr></tbody></table></th>
                  <th style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px auto;padding:0px;text-align:left;vertical-align:top;width:500px;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)"><table style="border-collapse:collapse;border-spacing:0px;box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tbody style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><th style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px;padding:0px;text-align:left;vertical-align:top;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)">
                    {!!  html_entity_decode($getMail->message) !!}

                    <table style="border-collapse:collapse;border-spacing:0px;box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tbody style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><td height="25" style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:25px;font-weight:normal;line-height:25px;margin:0px;padding:0px;text-align:left;vertical-align:top;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)">&nbsp;</td></tr></tbody></table>

                    <center style="box-sizing:border-box;min-width:500px;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif">
                      {{-- <table style="border-collapse:collapse;border-spacing:0px;box-sizing:border-box;float:none;margin:0px 0px 16px;padding:0px;text-align:center;vertical-align:top;width:auto;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tbody style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><td style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px;padding:0px;text-align:left;vertical-align:top;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)"><table style="border-collapse:collapse;border-spacing:0px;box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tbody style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><td style="border:none;border-radius:500px;box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px;padding:0px;text-align:left;vertical-align:top;word-break:normal;border-collapse:collapse!important;background-color:rgb(240,239,255);color:rgb(88,65,216)"><a align="center" href="https://www.kraken.com/sign-in" style="border:0px solid rgb(240,239,255);border-radius:69px;box-sizing:border-box;display:inline-block;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:700;line-height:1rem;margin-top:4px;min-width:260px;padding:14px 32px;text-align:center;text-decoration:none;color:rgb(88,65,216)" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://www.kraken.com/sign-in&amp;source=gmail&amp;ust=1692440433574000&amp;usg=AOvVaw0DNysTX3H3-WNni9oFhnjY">
                        Sign In
                      </a></td></tr></tbody></table></td></tr></tbody></table> --}}
                    </center>
                    <table style="border-collapse:collapse;border-spacing:0px;box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif;background-color:rgb(255,255,255)"><tbody style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><td height="10" style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:10px;font-weight:normal;line-height:10px;margin:0px;padding:0px;text-align:left;vertical-align:top;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)">&nbsp;</td></tr></tbody></table>

                    {{-- <p style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px;padding:0px;text-align:left;word-break:normal;color:rgb(36,36,36)">
                      If you don’t remember creating a Kraken account, consider contacting our <a href="https://support.kraken.com/hc/contact-support" style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-weight:normal;line-height:1.5em;padding:0px;text-align:left;text-decoration:underline;color:rgb(88,65,216)" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://support.kraken.com/hc/contact-support&amp;source=gmail&amp;ust=1692440433574000&amp;usg=AOvVaw0uRdZZinNMJoepdyRSPhua">Support Team</a>. We’ll be happy to provide more information.
                    </p> --}}

                  </th></tr></tbody></table></th>
                  <th style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px auto;padding:0px;text-align:left;vertical-align:top;width:50px;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)"><table style="border-collapse:collapse;border-spacing:0px;box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tbody style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><th style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px;padding:0px;text-align:left;vertical-align:top;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)"></th></tr></tbody></table></th>
                </tr></tbody></table>


                <table style="border-bottom-left-radius:15px;border-bottom-right-radius:15px;border-collapse:collapse;border-spacing:0px;box-sizing:border-box;display:table;padding:0px;text-align:left;vertical-align:top;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif;background-color:rgb(255,255,255)"><tbody style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif">
                  <th style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px auto;padding:0px;text-align:left;vertical-align:top;width:600px;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)"><table style="border-collapse:collapse;border-spacing:0px;box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tbody style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><th style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px;padding:0px;text-align:left;vertical-align:top;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)">
                    <table style="border-collapse:collapse;border-spacing:0px;box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tbody style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><td height="30" style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:30px;font-weight:normal;line-height:30px;margin:0px;padding:0px;text-align:left;vertical-align:top;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)">&nbsp;</td></tr></tbody></table>
                  </th>
    <th style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px;text-align:left;vertical-align:top;width:0px;word-break:normal;border-collapse:collapse!important;padding:0px!important;color:rgb(36,36,36)"></th></tr></tbody></table></th>
                </tr></tbody></table>

                <table style="border-collapse:collapse;border-spacing:0px;box-sizing:border-box;display:table;padding:0px;text-align:left;vertical-align:top;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif;background-color:transparent"><tbody style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif">
                  <th style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px auto;padding:0px;text-align:left;vertical-align:top;width:50px;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)"><table style="border-collapse:collapse;border-spacing:0px;box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tbody style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><th style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px;padding:0px;text-align:left;vertical-align:top;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)"> </th></tr></tbody></table></th>
                  <th style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px auto;padding:0px;text-align:left;vertical-align:top;width:500px;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)"><table style="border-collapse:collapse;border-spacing:0px;box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tbody style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><th style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px;padding:0px;text-align:left;vertical-align:top;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)">
                    <table style="border-collapse:collapse;border-spacing:0px;box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tbody style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><td height="30" style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:30px;font-weight:normal;line-height:30px;margin:0px;padding:0px;text-align:left;vertical-align:top;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)">&nbsp;</td></tr></tbody></table>

                    <table style="border-collapse:collapse;border-spacing:0px;box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tbody style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><td height="15" style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:15px;font-weight:normal;line-height:15px;margin:0px;padding:0px;text-align:left;vertical-align:top;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)">&nbsp;</td></tr></tbody></table>

                    <p style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:14px;font-weight:normal;letter-spacing:0.1px;line-height:1.4;margin:0px;padding:0px;text-align:center;word-break:normal;color:rgb(137,137,137)">© Kraken 2023</p>

                    <table style="border-collapse:collapse;border-spacing:0px;box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tbody style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><td height="14" style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:14px;font-weight:normal;line-height:14px;margin:0px;padding:0px;text-align:left;vertical-align:top;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)">&nbsp;</td></tr></tbody></table>

                    <p style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:14px;font-weight:normal;letter-spacing:0.1px;line-height:1.4;margin:0px;padding:0px;text-align:center;word-break:normal;color:rgb(137,137,137)">
                        100 Pine St., Suite 1250, PMB B297, San Francisco, CA 94111
                    </p>
                    <p style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:14px;font-weight:normal;letter-spacing:0.1px;line-height:1.4;margin:0px;padding:0px;text-align:center;word-break:normal;color:rgb(137,137,137)">
                      <a href="https://www.kraken.com/legal/disclosures" style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-weight:normal;line-height:1.5em;padding:0px;text-align:left;text-decoration:underline;color:rgb(137,137,137)" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://www.kraken.com/legal/disclosures&amp;source=gmail&amp;ust=1692440433574000&amp;usg=AOvVaw3a0Z-WiqKNTay1z1sFGwEx">Legal disclosures and licensing information</a>
                    </p>
                    <p style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:14px;font-weight:normal;letter-spacing:0.1px;line-height:1.4;margin:0px;padding:0px;text-align:center;word-break:normal;color:rgb(137,137,137)"></p>

                    <table style="border-collapse:collapse;border-spacing:0px;box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tbody style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><td height="14" style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:14px;font-weight:normal;line-height:14px;margin:0px;padding:0px;text-align:left;vertical-align:top;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)">&nbsp;</td></tr></tbody></table>

                    <center style="box-sizing:border-box;min-width:500px;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif">
                      <table align="center" style="border-collapse:collapse;border-spacing:0px;box-sizing:border-box;float:none;margin:0px auto;padding:0px;text-align:center;vertical-align:top;width:auto;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tbody style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><td style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px;padding:0px;text-align:left;vertical-align:top;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)"><table style="border-collapse:collapse;border-spacing:0px;box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tbody style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif">
                        <th style="box-sizing:border-box;float:none;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px auto;padding:0px 10px 0px 0px;text-align:center;vertical-align:top;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)"><a href="https://facebook.com/KrakenFX" style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-weight:normal;line-height:1.5em;padding:0px;text-align:left;text-decoration:underline;color:rgb(88,65,216)" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://facebook.com/KrakenFX&amp;source=gmail&amp;ust=1692440433574000&amp;usg=AOvVaw3zEhYzaQJDhOaobPcdZ5Qs">
                          <img src="https://ci3.googleusercontent.com/proxy/VBfPywsCU8NPnS_Ti0u6noCMSaqP_J4_IxnTDLfhTRrHGAerej0dgSIj42aavVVjku-nazaTUCw55oC6YsF-f4ymcVkXELgG9N2jsFPkfNfA=s0-d-e1-ft#https://assets.kraken.com/marketing/emails/social/Light-FB.png" alt="facebook logo" style="border:none;box-sizing:border-box;clear:both;display:block;height:25px;margin:0px 10px 1rem;max-width:100%;outline:none;text-decoration:none;width:25px;font-family:Celias,Roboto,Arial,Verdana,sans-serif" class="CToWUd" data-bit="iit">
                        </a></th>
                        <th style="box-sizing:border-box;float:none;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px auto;padding:0px 10px 0px 0px;text-align:center;vertical-align:top;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)"><a href="https://twitter.com/krakenfx" style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-weight:normal;line-height:1.5em;padding:0px;text-align:left;text-decoration:underline;color:rgb(88,65,216)" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://twitter.com/krakenfx&amp;source=gmail&amp;ust=1692440433574000&amp;usg=AOvVaw22Cq49RoHcVqG-YXewZCxO">
                          <img src="https://ci6.googleusercontent.com/proxy/qgZoeu06Wh3i_i6ze8Ys4uiyMuk0C9rW4UGQiZNhYXuRcc4ECQ9ppWirnWOg1MX0c82DlJB2_zSBDe5w4RE7x-Z19u2-QDxvk4nefKCf1PTyvgKncrc=s0-d-e1-ft#https://assets.kraken.com/marketing/emails/social/Light-Twitter.png" alt="twitter logo" style="border:none;box-sizing:border-box;clear:both;display:block;height:20px;margin:3px 10px 1rem;max-width:100%;outline:none;text-decoration:none;width:24px;font-family:Celias,Roboto,Arial,Verdana,sans-serif" class="CToWUd" data-bit="iit">
                        </a></th>
                        <th style="box-sizing:border-box;float:none;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px auto;padding:0px 10px 0px 0px;text-align:center;vertical-align:top;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)"><a href="https://www.instagram.com/krakenfx/" style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-weight:normal;line-height:1.5em;padding:0px;text-align:left;text-decoration:underline;color:rgb(88,65,216)" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://www.instagram.com/krakenfx/&amp;source=gmail&amp;ust=1692440433574000&amp;usg=AOvVaw35AGfq-ApYBdRztdOHaVTC">
                          <img src="https://ci6.googleusercontent.com/proxy/ozOzyLwNAD6IYcIYHdnXSorebtH0AgJZmwVihTSAS7zuFTISEd7Gnd_MoqLP8zcDrsYjKDIs8IfEvhwyyuJmT6vCyNsyNtiXahaUUbkakqA7=s0-d-e1-ft#https://assets.kraken.com/marketing/emails/social/Light-IG.png" alt="youtube logo" style="border:none;box-sizing:border-box;clear:both;display:block;height:25px;margin:0px 10px 1rem;max-width:100%;outline:none;text-decoration:none;width:25px;font-family:Celias,Roboto,Arial,Verdana,sans-serif" class="CToWUd" data-bit="iit">
                        </a></th>
                        <th style="box-sizing:border-box;float:none;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px auto;padding:0px 10px 0px 0px;text-align:center;vertical-align:top;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)"><a href="https://linkedin.com/company/krakenfx" style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-weight:normal;line-height:1.5em;padding:0px;text-align:left;text-decoration:underline;color:rgb(88,65,216)" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://linkedin.com/company/krakenfx&amp;source=gmail&amp;ust=1692440433574000&amp;usg=AOvVaw3Im3WzQ6reVPleo8lQlSkH">
                          <img src="https://ci4.googleusercontent.com/proxy/JreXwS9e0mLCjeKAblo_FaecrRdKzDeKPOGIxl47uaeTSlfp4_mKxQoLF62LaNSJQ1ezPYYJfMTTojHXsGAvVLy7H2UUACFoCXSYRH-jVwTx0vgAm8yy=s0-d-e1-ft#https://assets.kraken.com/marketing/emails/social/Light-Linkedin.png" alt="linkedin logo" style="border:none;box-sizing:border-box;clear:both;display:block;height:25px;margin:0px 10px 1rem;max-width:100%;outline:none;text-decoration:none;width:25px;font-family:Celias,Roboto,Arial,Verdana,sans-serif" class="CToWUd" data-bit="iit">
                        </a></th>
                        <th style="box-sizing:border-box;float:none;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px auto;padding:0px 10px 0px 0px;text-align:center;vertical-align:top;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)"><a href="https://www.youtube.com/c/KrakenBitcoinExchange" style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-weight:normal;line-height:1.5em;padding:0px;text-align:left;text-decoration:underline;color:rgb(88,65,216)" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://www.youtube.com/c/KrakenBitcoinExchange&amp;source=gmail&amp;ust=1692440433574000&amp;usg=AOvVaw0Hmri_UDgD1_rUEv0bbbhU">
                          <img src="https://ci6.googleusercontent.com/proxy/slYieZP2_7cVMhKvAC0f9JMh70uTrMzxmM3ajZnYNyw254pRRp4UpG4YlRAdfwP5coCljxzEznRJ6ikA4f3TLkd6XB0Sz4FzZkiC35DhYa_oJYETdTc=s0-d-e1-ft#https://assets.kraken.com/marketing/emails/social/Light-Youtube.png" alt="youtube logo" style="border:none;box-sizing:border-box;clear:both;display:block;height:15px;margin:5px 10px 1rem;max-width:100%;outline:none;text-decoration:none;width:20px;font-family:Celias,Roboto,Arial,Verdana,sans-serif" class="CToWUd" data-bit="iit">
                        </a></th>
                      </tr></tbody></table></td></tr></tbody></table>
                    </center>

                    <p style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;height:1px;line-height:1.5em;margin:0px;opacity:0;padding:0px;text-align:left;word-break:normal;color:rgba(0,0,0,0)">Anti-Trim: 64d7ee6aa3056</p>
                  </th></tr></tbody></table></th>
                  <th style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px auto;padding:0px;text-align:left;vertical-align:top;width:50px;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)"><table style="border-collapse:collapse;border-spacing:0px;box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;width:100%;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tbody style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><tr style="box-sizing:border-box;padding:0px;text-align:left;vertical-align:top;font-family:Celias,Roboto,Arial,Verdana,sans-serif"><th style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0px;padding:0px;text-align:left;vertical-align:top;word-break:normal;border-collapse:collapse!important;color:rgb(36,36,36)"></th></tr></tbody></table></th>
                </tr></tbody></table>
                </td></tr></tbody></table>
              </center>
              <p style="box-sizing:border-box;font-family:Celias,Roboto,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;height:1px;line-height:1.5em;margin:0px;opacity:0;padding:0px;text-align:left;word-break:normal;color:rgba(0,0,0,0)">Anti-Trim: 64d7ee6aa3056</p>
            </td>
          </tr>
        </tbody></table>

       <div style="box-sizing:border-box;display:none;font-style:normal;font-variant-caps:normal;font-weight:normal;font-stretch:normal;font-size:15px;font-family:courier;line-height:0;white-space:nowrap"> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </div>
      </div>
</body>
</html>
