<td style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">

    <table class="m_-7540048837813686860show-for-large" style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><td height="20" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:20px;font-weight:normal;line-height:20px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table>

    <table class="m_-7540048837813686860rounded-top" style="background:#ffffff;border-collapse:collapse;border-spacing:0;border-top-left-radius:15px;border-top-right-radius:15px;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><td height="30" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:30px;font-weight:normal;line-height:30px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table>

    <table style="background:#ffffff;border-collapse:collapse;border-spacing:0;box-sizing:border-box;display:table;padding:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top">
      <th class="m_-7540048837813686860small-1 m_-7540048837813686860columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
      <th class="m_-7540048837813686860small-5 m_-7540048837813686860columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:200px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
         <img src="https://ci4.googleusercontent.com/proxy/SbeF0VWMneCw9hj4jwcspfS0_uJuVC48eYyjgVc3kzIACv7BFAvebnqbfQzw8VaU1lXd5EgoodAfZD3yQmcffe3FEP3qsAvZSRhoNFAqcRgBZdqJ=s0-d-e1-ft#https://assets.kraken.com/marketing/emails/headers/Light-Logo.png" width="113" height="18" style="box-sizing:border-box;clear:both;display:block;max-width:100%;outline:none;text-decoration:none;width:auto" class="CToWUd" data-bit="iit">
      </th></tr></tbody></table></th>
      <th class="m_-7540048837813686860small-6 m_-7540048837813686860columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:350px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
    </tr></tbody></table>

    <table style="background:#ffffff;border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><td height="30" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:30px;font-weight:normal;line-height:30px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table>


    <table style="background:#ffffff;border-collapse:collapse;border-spacing:0;box-sizing:border-box;display:table;padding:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top">
      <th class="m_-7540048837813686860small-1 m_-7540048837813686860columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
      <th class="m_-7540048837813686860small-10 m_-7540048837813686860columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:500px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
        <h1 style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:#000000;font-family:'Celias','Roboto',Arial,Tahoma,sans-serif;font-size:30px;font-weight:700;line-height:1.5em;margin:0;margin-bottom:0px;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;word-wrap:normal">{!! html_entity_decode($subject) !!}
    </h1>
      </th></tr></tbody></table></th>
      <th class="m_-7540048837813686860small-1 m_-7540048837813686860columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
    </tr></tbody></table>

    <table style="background:#ffffff;border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><td height="25" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:25px;font-weight:normal;line-height:25px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table>

    <table style="background:#ffffff;border-collapse:collapse;border-spacing:0;box-sizing:border-box;display:table;padding:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top">
        <th class="m_-7540048837813686860small-1 m_-7540048837813686860columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:150px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
        <th class="m_-7540048837813686860small-10 m_-7540048837813686860columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:300px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
            <center style="box-sizing:border-box;min-width:300px;width:100%">
                <img src="https://ci5.googleusercontent.com/proxy/o1g9OiaVLf2hKqRz3U4YjCeEd8wA6GAjH6Xii5DTLIbT56iA96Y6G3ziPCNwAnmkU2GZorUryxSOzw2u8Xef__-6xkB1J3Zx9g9L1_KEx1-p7pKHLX0BmJvX0-dTgHTlMw=s0-d-e1-ft#https://assets.kraken.com/marketing/emails/header-illustrations/Light-Docs.png" align="center" style="Margin:0 auto;box-sizing:border-box;clear:both;display:block;float:none;margin:0 auto;max-width:100%;outline:none;text-align:center;text-decoration:none;width:auto" class="CToWUd a6T" data-bit="iit" tabindex="0"><div class="a6S" dir="ltr" style="opacity: 0.01; left: 477px; top: 319px;"><div id=":q8" class="T-I J-J5-Ji aQv T-I-ax7 L3 a5q" role="button" tabindex="0" aria-label="Download attachment " jslog="91252; u014N:cOuCgd,Kr2w4b,xr6bB; 4:WyIjbXNnLWY6MTc3NDU2NDgxMzQ0NDY0NTQ2MCIsbnVsbCxbXV0." data-tooltip-class="a1V" jsaction="JIbuQc:.CLIENT" data-tooltip="Download"><div class="akn"><div class="aSK J-J5-Ji aYr"></div></div></div></div>
            </center>
        </th></tr></tbody></table></th>
        <th class="m_-7540048837813686860small-1 m_-7540048837813686860columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:150px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
    </tr></tbody></table>

    <table style="background:#ffffff;border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><td height="25" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:25px;font-weight:normal;line-height:25px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table>

    <table style="background:#ffffff;border-collapse:collapse;border-spacing:0;box-sizing:border-box;display:table;padding:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top">
      <th class="m_-7540048837813686860small-1 m_-7540048837813686860columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
      <th class="m_-7540048837813686860small-10 m_-7540048837813686860columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:500px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
        <p style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;margin-bottom:0px;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;word-break:normal">
            {!! html_entity_decode($message) !!}
        </p>

        <table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><td height="25" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:25px;font-weight:normal;line-height:25px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table>


        <table style="background:#ffffff;border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><td height="10" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:10px;font-weight:normal;line-height:10px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table>


        <table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><td height="25" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:25px;font-weight:normal;line-height:25px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table>

        <p style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;margin-bottom:0px;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;word-break:normal">
          Our verification is automated and usually takes less than 5 minutes to complete.
        </p>

      </th></tr></tbody></table></th>
      <th class="m_-7540048837813686860small-1 m_-7540048837813686860columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
    </tr></tbody></table>

    <table style="background:#ffffff;border-collapse:collapse;border-spacing:0;box-sizing:border-box;display:table;padding:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top">
      <th class="m_-7540048837813686860small-1 m_-7540048837813686860columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"> </th></tr></tbody></table></th>
      <th class="m_-7540048837813686860small-10 m_-7540048837813686860columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:500px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
        <hr style="border:1px solid #cccccc;box-sizing:border-box;margin:30px auto;width:100%">
      </th></tr></tbody></table></th>
      <th class="m_-7540048837813686860small-1 m_-7540048837813686860columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"> </th></tr></tbody></table></th>
    </tr></tbody></table>

    <table style="background:#ffffff;border-collapse:collapse;border-spacing:0;box-sizing:border-box;display:table;padding:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top">
      <th class="m_-7540048837813686860small-1 m_-7540048837813686860columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
      <th class="m_-7540048837813686860small-10 m_-7540048837813686860columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:500px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
          <h2 style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:inherit;font-family:'Celias','Roboto',Arial,Tahoma,sans-serif;font-size:23px;font-weight:400;line-height:1.5em;margin:0;margin-bottom:0px;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;word-wrap:normal">What's next?</h2>
            <table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><td height="30" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:30px;font-weight:normal;line-height:30px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table>
        <table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;display:table;padding:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top">
          <th class="m_-7540048837813686860small-12 m_-7540048837813686860columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0!important;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:33.333333%;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
            <a href="https://www.youtube.com/watch?v=97lh_LjLYD4" style="box-sizing:border-box;color:#5841d8;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-weight:normal;line-height:1.5em;padding:0;text-align:left;text-decoration:underline" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://www.youtube.com/watch?v%3D97lh_LjLYD4&amp;source=gmail&amp;ust=1692462038756000&amp;usg=AOvVaw3FpnLv8l6NPkM70RqNAj0e">
              <img src="https://ci4.googleusercontent.com/proxy/tq-MOdCvjRC-a-mBGDgbgBlfNm-Uh7Yo6AJgSmxD8JWBF2Hh4Eq1WMavV2xjQKxh1K8LBo7m-ynWGPihqJ2BhPzRuBlCbH3vOFw6otp-5Ovbj_NKEdO3AQ=s0-d-e1-ft#https://assets.kraken.com/marketing/emails/body-illustrations/2FA.png" style="border:none;box-sizing:border-box;clear:both;display:block;max-width:100%;outline:none;text-decoration:none;width:auto" class="CToWUd" data-bit="iit">
            </a>
          </th></tr></tbody></table></th>
          <th class="m_-7540048837813686860small-4 m_-7540048837813686860columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
          </th></tr></tbody></table></th>
          <th class="m_-7540048837813686860small-12 m_-7540048837813686860columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:8.333333%;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
            <table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><td height="30" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:30px;font-weight:normal;line-height:30px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table>
          </th></tr></tbody></table></th>
          <th class="m_-7540048837813686860small-12 m_-7540048837813686860columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0!important;padding-top:0;text-align:left;vertical-align:top;width:58.333333%;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
            <strong style="box-sizing:border-box">
            Activate sign-in 2FA before your first transaction
            </strong>
            <table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><td height="14" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:14px;font-weight:normal;line-height:14px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table>
            <p style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;margin-bottom:0px;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;word-break:normal">
            Sign-in 2FA protects your account by asking for a unique code, on top of your password.
            </p>
          </th></tr></tbody></table></th>
        </tr></tbody></table>

      </th></tr></tbody></table></th>
      <th class="m_-7540048837813686860small-1 m_-7540048837813686860columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
    </tr></tbody></table>

    <table style="background:#ffffff;border-collapse:collapse;border-spacing:0;box-sizing:border-box;display:table;padding:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top">
      <th class="m_-7540048837813686860small-1 m_-7540048837813686860columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
      <th class="m_-7540048837813686860small-10 m_-7540048837813686860columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:500px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
        <table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><td height="14" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:14px;font-weight:normal;line-height:14px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table>
        <p style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;margin-bottom:0px;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;word-break:normal">
        Crypto is exciting and we want you to enjoy it to the fullest.
        Use our <a href="https://support.kraken.com/hc/articles/201396837" style="box-sizing:border-box;color:#5841d8;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-weight:normal;line-height:1.5em;padding:0;text-align:left;text-decoration:underline" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://support.kraken.com/hc/articles/201396837&amp;source=gmail&amp;ust=1692462038756000&amp;usg=AOvVaw2zWx1eItWNVImP2e4mVh0v">personal security guides</a> to keep your assets safe.
        </p>
      </th></tr></tbody></table></th>
      <th class="m_-7540048837813686860small-1 m_-7540048837813686860columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
    </tr></tbody></table>


    <table class="m_-7540048837813686860rounded-bottom" style="background:#ffffff;border-bottom-left-radius:15px;border-bottom-right-radius:15px;border-collapse:collapse;border-spacing:0;box-sizing:border-box;display:table;padding:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top">
      <th class="m_-7540048837813686860small-12 m_-7540048837813686860columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:600px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
        <table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><td height="30" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:30px;font-weight:normal;line-height:30px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table>
      </th>
<th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding:0!important;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:0;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
    </tr></tbody></table>

    <table class="m_-7540048837813686860collapse" style="background:transparent;border-collapse:collapse;border-spacing:0;box-sizing:border-box;display:table;padding:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top">
      <th class="m_-7540048837813686860small-1 m_-7540048837813686860columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"> </th></tr></tbody></table></th>
      <th class="m_-7540048837813686860small-10 m_-7540048837813686860columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:500px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
        <table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><td height="30" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:30px;font-weight:normal;line-height:30px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table>

        <table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><td height="15" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:15px;font-weight:normal;line-height:15px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table>

        <p style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:#898989!important;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:14px;font-weight:normal;letter-spacing:0.1px;line-height:1.4;margin:0;margin-bottom:0px;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:center;word-break:normal">© Kraken 2023</p>

        <table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><td height="14" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:14px;font-weight:normal;line-height:14px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table>

        <p style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:#898989!important;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:14px;font-weight:normal;letter-spacing:0.1px;line-height:1.4;margin:0;margin-bottom:0px;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:center;word-break:normal">
            100 Pine St., Suite 1250, PMB B297, San Francisco, CA 94111
        </p>
        <p style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:#898989!important;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:14px;font-weight:normal;letter-spacing:0.1px;line-height:1.4;margin:0;margin-bottom:0px;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:center;word-break:normal">
          <a href="https://www.kraken.com/legal/disclosures" style="box-sizing:border-box;color:#898989!important;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-weight:normal;line-height:1.5em;padding:0;text-align:left;text-decoration:underline" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://www.kraken.com/legal/disclosures&amp;source=gmail&amp;ust=1692462038756000&amp;usg=AOvVaw09nF3HF93xiW-kc4j06XnZ">Legal disclosures and licensing information</a>
        </p>
        <p style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:#898989!important;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:14px;font-weight:normal;letter-spacing:0.1px;line-height:1.4;margin:0;margin-bottom:0px;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:center;word-break:normal"></p>

        <table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><td height="14" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:14px;font-weight:normal;line-height:14px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table>

        <center style="box-sizing:border-box;min-width:500px;width:100%">
          <table align="center" class="m_-7540048837813686860menu" style="Margin:0 auto;border-collapse:collapse;border-spacing:0;box-sizing:border-box;float:none;margin:0 auto;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:center;vertical-align:top;width:auto"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><td style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top">
            <th style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;float:none;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding:10px;padding-bottom:0;padding-left:0;padding-right:10px;padding-top:0;text-align:center;vertical-align:top;word-break:normal;word-wrap:break-word"><a href="https://facebook.com/KrakenFX" style="box-sizing:border-box;color:#5841d8;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-weight:normal;line-height:1.5em;padding:0;text-align:left;text-decoration:underline" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://facebook.com/KrakenFX&amp;source=gmail&amp;ust=1692462038756000&amp;usg=AOvVaw2BHbYP1p5yQt9aOb5h7FZZ">
              <img class="m_-7540048837813686860social-icon CToWUd" src="https://ci3.googleusercontent.com/proxy/VBfPywsCU8NPnS_Ti0u6noCMSaqP_J4_IxnTDLfhTRrHGAerej0dgSIj42aavVVjku-nazaTUCw55oC6YsF-f4ymcVkXELgG9N2jsFPkfNfA=s0-d-e1-ft#https://assets.kraken.com/marketing/emails/social/Light-FB.png" alt="facebook logo" style="border:none;box-sizing:border-box;clear:both;display:block;height:25px;margin:0 10px 0 10px;margin-bottom:1rem;max-width:100%;outline:none;text-decoration:none;width:25px" data-bit="iit">
            </a></th>
            <th style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;float:none;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding:10px;padding-bottom:0;padding-left:0;padding-right:10px;padding-top:0;text-align:center;vertical-align:top;word-break:normal;word-wrap:break-word"><a href="https://twitter.com/krakenfx" style="box-sizing:border-box;color:#5841d8;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-weight:normal;line-height:1.5em;padding:0;text-align:left;text-decoration:underline" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://twitter.com/krakenfx&amp;source=gmail&amp;ust=1692462038756000&amp;usg=AOvVaw0DtZxWRrbJI1fpFzLFaIRT">
              <img class="m_-7540048837813686860social-icon m_-7540048837813686860social-icon-twitter CToWUd" src="https://ci6.googleusercontent.com/proxy/qgZoeu06Wh3i_i6ze8Ys4uiyMuk0C9rW4UGQiZNhYXuRcc4ECQ9ppWirnWOg1MX0c82DlJB2_zSBDe5w4RE7x-Z19u2-QDxvk4nefKCf1PTyvgKncrc=s0-d-e1-ft#https://assets.kraken.com/marketing/emails/social/Light-Twitter.png" alt="twitter logo" style="border:none;box-sizing:border-box;clear:both;display:block;height:20px;margin:0 10px 0 10px;margin-bottom:1rem;margin-top:3px;max-width:100%;outline:none;text-decoration:none;width:24px" data-bit="iit">
            </a></th>
            <th style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;float:none;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding:10px;padding-bottom:0;padding-left:0;padding-right:10px;padding-top:0;text-align:center;vertical-align:top;word-break:normal;word-wrap:break-word"><a href="https://www.instagram.com/krakenfx/" style="box-sizing:border-box;color:#5841d8;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-weight:normal;line-height:1.5em;padding:0;text-align:left;text-decoration:underline" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://www.instagram.com/krakenfx/&amp;source=gmail&amp;ust=1692462038756000&amp;usg=AOvVaw0OFbYvn5ELjbrsNG1_e7NF">
              <img class="m_-7540048837813686860social-icon CToWUd" src="https://ci6.googleusercontent.com/proxy/ozOzyLwNAD6IYcIYHdnXSorebtH0AgJZmwVihTSAS7zuFTISEd7Gnd_MoqLP8zcDrsYjKDIs8IfEvhwyyuJmT6vCyNsyNtiXahaUUbkakqA7=s0-d-e1-ft#https://assets.kraken.com/marketing/emails/social/Light-IG.png" alt="youtube logo" style="border:none;box-sizing:border-box;clear:both;display:block;height:25px;margin:0 10px 0 10px;margin-bottom:1rem;max-width:100%;outline:none;text-decoration:none;width:25px" data-bit="iit">
            </a></th>
            <th style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;float:none;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding:10px;padding-bottom:0;padding-left:0;padding-right:10px;padding-top:0;text-align:center;vertical-align:top;word-break:normal;word-wrap:break-word"><a href="https://linkedin.com/company/krakenfx" style="box-sizing:border-box;color:#5841d8;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-weight:normal;line-height:1.5em;padding:0;text-align:left;text-decoration:underline" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://linkedin.com/company/krakenfx&amp;source=gmail&amp;ust=1692462038756000&amp;usg=AOvVaw127mg6ZbtZauUAUUCHJB2X">
              <img class="m_-7540048837813686860social-icon CToWUd" src="https://ci4.googleusercontent.com/proxy/JreXwS9e0mLCjeKAblo_FaecrRdKzDeKPOGIxl47uaeTSlfp4_mKxQoLF62LaNSJQ1ezPYYJfMTTojHXsGAvVLy7H2UUACFoCXSYRH-jVwTx0vgAm8yy=s0-d-e1-ft#https://assets.kraken.com/marketing/emails/social/Light-Linkedin.png" alt="linkedin logo" style="border:none;box-sizing:border-box;clear:both;display:block;height:25px;margin:0 10px 0 10px;margin-bottom:1rem;max-width:100%;outline:none;text-decoration:none;width:25px" data-bit="iit">
            </a></th>
            <th style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;float:none;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding:10px;padding-bottom:0;padding-left:0;padding-right:10px;padding-top:0;text-align:center;vertical-align:top;word-break:normal;word-wrap:break-word"><a href="https://www.youtube.com/c/KrakenBitcoinExchange" style="box-sizing:border-box;color:#5841d8;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-weight:normal;line-height:1.5em;padding:0;text-align:left;text-decoration:underline" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://www.youtube.com/c/KrakenBitcoinExchange&amp;source=gmail&amp;ust=1692462038757000&amp;usg=AOvVaw1bmgZdKqHe7rOXK6EmoJ9m">
              <img class="m_-7540048837813686860social-icon m_-7540048837813686860social-icon-youtube CToWUd" src="https://ci6.googleusercontent.com/proxy/slYieZP2_7cVMhKvAC0f9JMh70uTrMzxmM3ajZnYNyw254pRRp4UpG4YlRAdfwP5coCljxzEznRJ6ikA4f3TLkd6XB0Sz4FzZkiC35DhYa_oJYETdTc=s0-d-e1-ft#https://assets.kraken.com/marketing/emails/social/Light-Youtube.png" alt="youtube logo" style="border:none;box-sizing:border-box;clear:both;display:block;height:15px;margin:0 10px 0 10px;margin-bottom:1rem;margin-top:5px;max-width:100%;outline:none;text-decoration:none;width:20px" data-bit="iit">
            </a></th>
          </tr></tbody></table></td></tr></tbody></table>
        </center>

        <p style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:rgba(0,0,0,0)!important;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;height:1px;line-height:1.5em;margin:0;margin-bottom:0px;opacity:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;word-break:normal">Anti-Trim: 64df511313107</p>
      </th></tr></tbody></table></th>
      <th class="m_-7540048837813686860small-1 m_-7540048837813686860columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
    </tr></tbody></table>
    </td>
